dist: trusty
language: rust
services: docker
sudo: true

env:
  global:
    - CRATE_NAME=libwebp-rust

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly

addons:
  apt:
    packages:
      - libwebp-dev
      - libclang-dev
      - clang

before_install:
  - set -e
  - rustup self update

install:
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh
  - cargo doc && echo "<meta http-equiv=refresh content=0;url=`echo libwebp_rust | cut -d '/' -f 2`/index.html>" > target/doc/index.html

after_script: set +e

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $gh
  keep_history: true
  local_dir: target/doc
  on:
    branch: master

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
